# _config.yml
title: "Alejandro Aznar Casado"
name:  "Alejandro Aznar Casado"
description: "Data science & Biostat in Pharma · R · Python · Power BI"
url: "https://alaznar.github.io"
baseurl: ""
logo: /assets/img/alejandro-aznar.jpg
timezone: Europe/Madrid

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "aqua"   # otras skins: default, dark, neon, sunrise...

lang: en
search: true
permalink: /:categories/:title/

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

author:
  name: "Alejandro Aznar Casado"
  avatar: /assets/img/1alejandro-aznar.jpg
  bio: "Biotech → Data/Stats en farma. R, Python, Power BI. Safety/Clinical Data."
  location: "Madrid, Spain"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:alaznar01@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://es.linkedin.com/in/alejandroaznar-"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/alaznar"

# Colección de proyectos (para tener /projects con fichas)
collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope: { path: "", type: "projects" }
    values:
      layout: single
      author_profile: true
      classes: wide
      read_time: false
      share: false

# Analítica (opcional)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XXXXXXXXXX"
