---
title: "Diabetes Multiclass Prediction"
excerpt: "Garmin activities analysis, vizualization and modeling"
teaser: /assets/img/garmin_teaser.png
---

***Challenge*** Explore workouts and sleep data generated by a Garmin Forerunner 265S sportwatch

***Focus*** Data cleaning and *feature engineering*; automation of data extraction, transformation and loading (ETL); Visualization with Matplotlib; *Notebook* discussion.

***Results*** Dashboard with key metrics (heart rate, distance, sleep) which allow data tracking with ease.

***Stack*** Python · Matplotlib · statsmodels · Jupyter

- [Repo](https://github.com/alaznar/Garmin-Data>)
- [Notebook](https://nbviewer.org/github/alaznar/Diabetes-class/blob/374b7c248acb870380d328dded5df736b89bccc4/Diabetes.ipynb)
